config/routes.rb
Rails.application.routes.draw do
  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  root 'static_pages#home', controller: "application#index"
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'



  resources :locations, :categories, :courses do
    member do
      get :categories
      get :courses
      post :course_add
      post :course_remove
      post :category_add
      post :category_remove
      post :courses_thumbsup
      post :courses_thumbsdown 
    end
  end
  resources :users

  resources :courses do
    resources :likes
    resources :unlikes
  end

  resources :contact, only: [:new, :create, :edit ]
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/models/course.rb
class Course < ApplicationRecord
  has_and_belongs_to_many :categories, dependent: :destroy
  has_and_belongs_to_many :locations, dependent: :destroy
  has_many :users
  has_many :likes, dependent: :destroy
  has_many :unlikes, dependent: :destroy
  has_one_attached :avatar

validates :name,  presence: true, length: { minimum: 10}
validates :prerequisite,  presence: true, length: { minimum: 10}
validates :description, presence: true, length: { minimum: 30}


  def enrolled_in?(category)
      self.categories.include?(category)
  end

  def unenrolled_categories
    Category.all - self.categories
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :destroy]
  skip_before_action :verify_authenticity_token

  def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course_params = params.require(:course).permit(:user_id ,:name, :prerequisite,:description,
      {category_ids:[]},
      {location_ids:[]},
      :avatar)
    
    @course = Course.new(@course_params)
    
    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @courses }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @courses }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def categories
    @course = Course.find(params[:id])
    @categories = @course.categories
  end

  def likes 
    @likes = Like.all
    @likes.destroy
  end

  def category_add
  #Convert ids from routing to objects
    @course = Course.find(params[:id])
    @category = Category.find(params[:category])

    unless @course.enrolled_in?(@category)
      #add course to list using << operator
      @course.categories << @category
      flash[:notice] = 'Course was successfully enrolled in category '
    else
       flash[:error] = 'Course was already enrolled'
    end
    redirect_to action: "categories", id: @course
  end

  def category_remove
  #Convert ids from routing to object
  @course = Course.find( params[:id])

  #get list of courses to remove from query string
  category_ids = params[:categories]
  if category_ids.any?
    category_ids.each do |category_ids|
      category = Category.find(category_ids)

      if @course.enrolled_in?(category)
        logger.info "Removing course from Category #{category.id}"
        @course.categories.delete(category)
        flash[:notice] = 'Category was successfully deleted'
      end
    end
  end
  redirect_to action: "categories", id: @course
  end

  def roll
    @course = Course.find(params[:id])
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:user_id ,:name, :prerequisite,:description,
      {category_ids:[]},
      {location_ids:[]},
      :avatar)
    end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
<%= render 'shared/error_messages0', object: @course %>


  <%=form.hidden_field :user_id, value: current_user.id %>

    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>

    <%= form.label :prerequisite %>
    <%= form.text_area :prerequisite, class: 'form-control' %>

    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>

    <%= form.label :categories %>
            <% for category in Category.all %>
            <%= category.name %>
            <%= check_box_tag "course[category_ids][]", category.id,
                @course.categories.include?(category) %>
            <% end %>

          <%#= course.categories.map(&:name).join(', ') %>
       
          <p>Description:  <%= course.description %></p>

          <p>Location: 
         <%= form.label :locations %>
              <% for location in Location.all %>
              <%= location.name %>
              <%= check_box_tag "course[location_ids][]", location.id,
                  @course.locations.include?(location) %>
              <% end %>

      <%= form.label "course photo" %>
      <%= form.file_field :avatar, class: 'form-control'  %>

   

    <%= form.submit %>

<% end %>

app/views/courses/categories.html.erb
<h1> <%= @course.name %>'s category list </h1> 

<% if @categories.length > 0 %> 
  <%= form_tag( category_remove_course_path(@course)) do %> 
  <table> 
    <thead> 
      <tr> 
        <th> Category </th> 
        <th> Remove? </th> 
      </tr> 
    </thead>
    
    <tbody> 
    <% for category in @categories do %> 
      <tr> <td> <%= category.name %> </td> 
           <td> <%= check_box_tag "categories[]", category.id %> </td> </tr>
    <% end %> 
   </tbody> 
   </table > <br /> 
         
    <%= submit_tag 'Remove checked categories' %>
         
  <% end %> 
<% else %> 
  <p> Not added to any category yet. </p> 
<% end %> 
    
<h2> Enroll in new category </h2>

<% if @course.categories.count < Category.count then %> 
  <%= form_tag( category_add_course_path(@course)) do %> 
      <%= select_tag(:category, 
          options_from_collection_for_select(@course.unenrolled_categories, :id, :name)) %> 
      <%= submit_tag 'Enroll' %> 
  <% end %> 
<% end %> 
<p> <%= link_to 'Back', @course %> </p>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>



<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>All Courses</h1>
<%= render 'course_nav' %>

<%# if current_user.admin? %>
<%#= button_to 'Reset votes', course_unlikes_path(@courses), method: :delete %>
<%# end %>

<% @courses.each do |course| %>

<div class="row">

  <div class="col-md-3" >

    <%= gravatar_for User.find(course.user_id) %>
    <div style="display:block">
    <%=  User.find(course.user_id).name %>
    </div>


  </div>
  <div class="col-md-9" >

      <div class="details" >

          <p>Name:  <%= link_to course.name, course %></p>
          <p>Prerequisite: <%= course.prerequisite %></p>
          <p>Category:

            <% if !course.categories.empty? %>
              <%= course.categories.collect {|c|
                link_to( c.name, c)}.join(", ").html_safe %>
            <% else %>
              Not added to any category yet.
            <% end %>

            <p> Locations:
                <% if !course.locations.empty? %>
                  <%= course.locations.collect {|c|
                    link_to( c.name, c)}.join(", ").html_safe %>
                <% else %>
                No location added to this course.
                <% end %>
              </p>

          


          <p> Created: <%= time_ago_in_words(course.created_at) %></p>





      <% if logged_in? %>
            <% if current_user.admin? || current_user == User.find(course.user_id) %>
              <%= link_to 'Edit', edit_course_path(course), class:'white-text btn btn-success btn-lg'%>
                <% if current_user.admin? %>

                    <%# <%= button_to 'Reset votes', course.like, method: :delete %>

                    <%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %><br>
                <% end %>
            <% end %>

        <% pre_like = course.likes.find { |like| like.user_id == current_user.id} %>
        <% pre_unlike = course.unlikes.find { |unlike| unlike.user_id == current_user.id} %>
        <% if !pre_like || !pre_unlike%>
          <%= link_to 'Like', course_likes_path(course), method: :post, class:'white-text btn btn-success btn-lg glyphicon glyphicon-thumbs-up' %>
          <%= link_to 'UnLike', course_unlikes_path(course), method: :post, class:'white-text btn btn-success btn-lg glyphicon glyphicon-thumbs-down' %>

          <% else %>
           <%= link_to 'Like', course_likes_path(course), method: :post, class:'white-text btn btn-success btn-lg glyphicon glyphicon-thumbs-up' %>
           <%= link_to 'UnLike', course_unlikes_path(course), method: :post, class:'white-text btn btn-success btn-lg glyphicon glyphicon-thumbs-up' %>
        <% end %>
        <%else%>
         <button type="submit" class="btn btn-success btn-lg">
            <span class = "glyphicon glyphicon-thumbs-up">
              <%= link_to 'Like', login_path %></span>
          </button>

          <button type="submit" class="btn btn-success btn-lg">
            <span class = "glyphicon glyphicon-thumbs-down">
              </span><%= link_to '  UnLike', login_path %>
          </button>


       </div><br><br>
       <% end %>
       <p><%= course.likes.count %> <%= (course.likes.count) == 1 ? 'Like' : 'Likes'%></p>
        <p><%= course.unlikes.count %> <%= (course.unlikes.count) == 1 ? 'Unlike' : 'Unlikes'%></p>
  </div>

</div>

<% end %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<h1> Course: <%= @course.name %> </h1>

  <div class="col-md-3" >

    <%= gravatar_for User.find(@course.user_id) %>
    <%=  User.find(@course.user_id).name %>


      </div>
    <div class="col-md-8" >
     <div class="details" >
      <p>
        <strong>Name:</strong>
        <%= @course.name %>
      </p>

      <p>
        <strong>Prerequisite:</strong>
        <%= @course.prerequisite %>
      </p>

      <p>
        <strong>Category:</strong>

          <% if !@course.categories.empty? %>
            <%= @course.categories.collect {|c|
              link_to( c.name, c)}.join(", ").html_safe %>
          <% else %>
            Not added to any category yet.
          <% end %>

      </p>

      <p>
         <strong>Location:</strong>
         <% if !@course.locations.empty? %>
            <%= @course.locations.collect {|c|
              link_to( c.name, c)}.join(", ").html_safe %>
          <% else %>
           No location added to this course.
          <% end %>
      </p>

      <p>
        <strong>Created:</strong>
          <%= time_ago_in_words(@course.created_at) %>
      </p>
         </div>

      <% if logged_in? %>
          <% if current_user.admin? || current_user == User.find(@course.user_id) %>
            <%= link_to 'Edit', edit_course_path(@course), class:'white-text btn btn-success btn-lg' %>
              <% if current_user.admin? %>

                  <%# <%= button_to 'Reset votes', course.like, method: :delete %>

                  <%= link_to 'Destroy', @course, method: :delete, data: { confirm: 'Are you sure?' } %><br>
              <% end %>
           <% end %>

        <% pre_like = @course.likes.find { |like| like.user_id == current_user.id} %>
        <% pre_unlike = @course.unlikes.find { |unlike| unlike.user_id == current_user.id} %>
            <% if !pre_like || !pre_unlike%>
              <%= link_to 'Like', course_likes_path(@course), method: :post, class:'white-text btn btn-success btn-lg glyphicon glyphicon-thumbs-up' %>
              <%= link_to 'UnLike', course_unlikes_path(@course), method: :post, class:'white-text btn btn-success btn-lg glyphicon glyphicon-thumbs-down' %>

            <% else %>
              <%= link_to 'Like', course_likes_path(@course), method: :post, class:'white-text btn btn-success btn-lg glyphicon glyphicon-thumbs-up' %>
              <%= link_to 'UnLike', course_unlikes_path(@course), method: :post, class:'white-text btn btn-success btn-lg glyphicon glyphicon-thumbs-up' %>
             <% end %>
        <% else %>
          <%= link_to 'Like', login_path, class:'white-text btn btn-success btn-lg glyphicon glyphicon-thumbs-up' %>
          <%= link_to 'UnLike', login_path, class:'white-text btn btn-success btn-lg glyphicon glyphicon-thumbs-down' %>

      <% end %>
    <p><%= @course.likes.count %> <%= (@course.likes.count) == 1 || 0 ? 'Like' : 'Likes'%></p>
    <p><%= @course.unlikes.count %> <%= (@course.unlikes.count) == 1 || 0 ? 'Unlike' : 'Unlikes'%></p>

</div>


<div class="col-md-4" >
  <% if @course.avatar.attached? %>
        <image height="200" width="200" src="<%= (url_for(@course.avatar))%>">

  <%end%>
</div>