config/routes.rb
Rails.application.routes.draw do
  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  root 'static_pages#home', controller: "application#index"
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'



  resources :locations, :categories, :courses do
    member do
      get :categories
      get :courses
      post :course_add
      post :course_remove
      post :category_add
      post :category_remove
      post :courses_thumbsup
      post :courses_thumbsdown 
    end
  end
  resources :users

  resources :courses do
    resources :likes
    resources :unlikes
  end

  resources :contact, only: [:new, :create, :edit ]
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/models/category.rb
class Category < ApplicationRecord
	has_and_belongs_to_many :courses, dependent: :destroy

	def enrolled_in?(course) 
      self.courses.include?(course) 
    end
    
    def unenrolled_courses
      Course.all - self.courses 
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
    @courses = @category.courses
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def courses
    @category = Category.find(params[:id])
    @courses = @category.courses
  end
  
  def course_add 
  #Convert ids from routing to objects 
  @category = Category.find(params[:id])
  @course = Course.find(params[:course])
  unless @category.enrolled_in?(@course) 
    #add course to list using << operator 
    @category.courses << @course 
    flash[:notice] = 'Category was successfully enrolled' 
  else 
     flash[:error] = 'Category was already enrolled' 
  end 
  redirect_to action: "courses", id: @category 
  end

  def course_remove 
  #Convert ids from routing to object 
  @category = Category.find( params[:id]) 
  
  #get list of courses to remove from query string
  course_ids = params[:courses] 
  if course_ids.any? 
    course_ids.each do |course_id| 
      course = Course.find(course_id) 
      if @category.enrolled_in?(course)
        logger.info "Removing category from course #{course.id}" 
        @category.courses.delete(course) 
        flash[:notice] = 'Course was successfully deleted'
      end 
    end 
  end 
  redirect_to action: "courses", id: @category 
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :courses)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/courses.html.erb
<h1> <%= "All courses in " + @category.name + " category "%> </h1> 

<% if @category.courses.length > 0 %>

<%= form_tag( course_remove_category_path(@category)) do %>

<table>
	<thead>
		<tr>
			<th> Course </th>
			<th> Remove? </th>
		</tr>
	</thead>

	<tbody>
		<% for course in @courses do %>
		<tr> <td> <%= course.name %> </td>
			 <td> <%= check_box_tag "courses[]", course.id %> </td> 
		</tr>
		<% end %>
	</tbody>

</table > <br />

<%= submit_tag 'Remove checked courses' %>

<% end %>
<% else %>
	<p> Not enrolled in any courses yet. </p>
	<%= link_to 'Create new Course', new_course_path %>
<% end %>

<h2> Enroll in new course </h2>

<% if @category.courses.count < Course.count then %> 
  <%= form_tag( course_add_category_path(@category)) do %> 
      <%= select_tag(:course, 
          options_from_collection_for_select(@category.unenrolled_courses, :id, :name)) %> 
      <%= submit_tag 'Add' %> 
  <% end %> 
<% else %> 
  <p>Category already has all courses</p>
<% end %> 
<p> <%= link_to 'Back', @category %> </p>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses in <%= @categories.name%></h1>


 <% @categories.each do |category| %>
 <div class="row">
    <div class="col-md-8" >

      <div class="details" >
   
            <p>Category Name: <%= link_to category.name, category %></p>
              <p>Courses: <%= category.courses.collect {|c| 
              link_to( c.name, c)}.join(" , ").html_safe %></p><br>
              
      </div> <br><br>
  </div>
</div>
<% end %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses in <%= @category.name %> </h1>

<%= render 'course_nav' %>
<% if @category.courses.count < 1 %>
  <h4 style="text-align: center;">No courses are allocated to this category.</h4>

<% else %>
      <% @category.courses.each do |course| %>
  <div class="col-md-3" >

    <%= gravatar_for User.find(course.user_id) %>
    <%=  User.find(course.user_id).name %>


      </div>
    <div class="col-md-8" >
     <div class="details" >
          <p>

      <h4><%= link_to course.name, course %></h4>

      <p>Prerequisite: <%= course.prerequisite %></p>
       <strong>Category:</strong>
          <% if !course.categories.empty? %>
            <%= course.categories.collect {|c|
              link_to( c.name, c)}.join(", ").html_safe %>
          <% else %>
            Not added to any category yet.
          <% end %>
        </h4>
        
        <h4><strong>Location:</strong>
         <% if !course.locations.empty? %>
            <%= course.locations.collect {|c|
              link_to( c.name, c)}.join(", ").html_safe %>
          <% else %>
           No location added to this course.
          <% end %>
        </h4>
     <p>
        Created: <%= time_ago_in_words(course.created_at) %>
      </p>
        <% if logged_in? %>
            <% if current_user.admin? || current_user == User.find(course.user_id) %>
              <%= link_to 'Edit', edit_course_path(course) %>
                <% if current_user.admin? %>
              
                    <%# <%= button_to 'Reset votes', course.like, method: :delete %>

                    <%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %><br>
                <% end %>
            <% end %>

        <% pre_like = course.likes.find { |like| like.user_id == current_user.id} %>
        <% pre_unlike = course.unlikes.find { |unlike| unlike.user_id == current_user.id} %>
        <% if !pre_like || !pre_unlike%>
          <%= link_to 'Like', course_likes_path(course), method: :post, class:'white-text btn btn-success btn-lg glyphicon glyphicon-thumbs-up' %>
          <%= link_to 'UnLike', course_unlikes_path(course), method: :post, class:'white-text btn btn-success btn-lg glyphicon glyphicon-thumbs-down' %>

          <% else %>
           <%= link_to 'Like', course_likes_path(course), method: :post, class:'white-text btn btn-success btn-lg glyphicon glyphicon-thumbs-up' %>
           <%= link_to 'UnLike', course_unlikes_path(course), method: :post, class:'white-text btn btn-success btn-lg glyphicon glyphicon-thumbs-up' %>
        <% end %>
        <%else%>
          <%= link_to 'Like', login_path, class:'white-text btn btn-success btn-lg glyphicon glyphicon-thumbs-up' %>
          <%= link_to 'UnLike', login_path, class:'white-text btn btn-success btn-lg glyphicon glyphicon-thumbs-down' %>
    
      <% end %>
    <p><%= course.likes.count %> <%= (course.likes.count) == 1 || 0 ? 'Like' : 'Likes'%></p>
    <p><%= course.unlikes.count %> <%= (course.unlikes.count) == 1 || 0 ? 'Unlike' : 'Unlikes'%></p>
   <% end %>
<% end %>