config/routes.rb
Rails.application.routes.draw do
  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  root 'static_pages#home', controller: "application#index"
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'



  resources :locations, :categories, :courses do
    member do
      get :categories
      get :courses
      post :course_add
      post :course_remove
      post :category_add
      post :category_remove
      post :courses_thumbsup
      post :courses_thumbsdown 
    end
  end
  resources :users

  resources :courses do
    resources :likes
    resources :unlikes
  end

  resources :contact, only: [:new, :create, :edit ]
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/models/location.rb
class Location < ApplicationRecord
	has_and_belongs_to_many :courses, dependent: :destroy

	def enrolled_in?(course) 
      self.courses.include?(course) 
    end
    
    def unenrolled_courses
      Course.all - self.courses 
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])
    @courses = @location.courses
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def courses
    @location = Location.find(params[:id])
    @courses = @location.courses
  end

  def course_add 
  #Convert ids from routing to objects 
  @location = Location.find(params[:id])
  @course = Course.find(params[:course])
  unless @location.enrolled_in?(@course) 
    #add course to list using << operator 
    @location.courses << @course 
    flash[:notice] = 'Location was successfully enrolled' 
  else 
     flash[:error] = 'Location was already enrolled' 
  end 
  redirect_to action: "courses", id: @location 
  end

  def course_remove 
  #Convert ids from routing to object 
  @location = Location.find( params[:id]) 
  
  #get list of courses to remove from query string
  course_ids = params[:courses] 
  if course_ids.any? 
    course_ids.each do |course_id| 
      course = Course.find(course_id) 
      if @location.enrolled_in?(course)
        logger.info "Removing location from course #{course.id}" 
        @location.courses.delete(course) 
        flash[:notice] = 'Course was successfully deleted'
      end 
    end 
  end 
  redirect_to action: "courses", id: @location 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :courses)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_with(model: location, local: true) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :location_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/courses.html.erb
<h1> <%= "Courses scheduled in location " + @location.name %> </h1> 

<% if @location.courses.length > 0 %>

<%= form_tag( course_remove_location_path(@location)) do %>

<table>
	<thead>
		<tr>
			<th> Course </th>
			<th> Remove? </th>
		</tr>
	</thead>

	<tbody>
		<% for course in @courses do %>
		<tr> <td> <%= course.name %> </td>
			 <td> <%= check_box_tag "courses[]", course.id %> </td> 
		</tr>
		<% end %>
	</tbody>

</table > <br />

<%= submit_tag 'Remove checked courses' %>

<% end %>
<% else %>
	<p> Not enrolled in any courses yet. </p>
	<%= link_to 'Create new Course', new_course_path %>
<% end %>

<h2> Enroll in new course </h2>

<% if @location.courses.count < Course.count then %> 
  <%= form_tag( course_add_location_path(@location)) do %> 
      <%= select_tag(:course, 
          options_from_collection_for_select(@location.unenrolled_courses, :id, :name)) %> 
      <%= submit_tag 'Add' %> 
  <% end %> 
<% else %> 
  <p>Category already has all courses</p>
<% end %> 
<p> <%= link_to 'Back', @location %> </p>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locations</h1>


    <% @locations.each do |location| %>
   <div class="row">
    <div class="col-md-8" >

      <div class="details" >
        <p>Location: <%= link_to location.name, location %></p>
        <p>Courses: <%= location.courses.collect {|c| 
        link_to( c.name, c)}.join(",").html_safe %></p>
        
      </div> <br><br>
    </div>
  </div>
<% end %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses in <%= @location.name %> </h1>

<%= render 'course_nav' %>
<% if @location.courses.count < 1 %>
  <h4 style="text-align: center;">No courses are allocated to this location.</h4>

<% else %>
      <% @location.courses.each do |course| %>
  <div class="col-md-3" >

    <%= gravatar_for User.find(course.user_id) %>
    <%=  User.find(course.user_id).name %>


      </div>
    <div class="col-md-8" >
     <div class="details" >
          <p>

      <h4><%= link_to course.name, course %></h4>

      <p>Prerequisite: <%= course.prerequisite %></p>
       <strong>Category:</strong>
          <% if !course.categories.empty? %>
            <%= course.categories.collect {|c|
              link_to( c.name, c)}.join(", ").html_safe %>
          <% else %>
            Not added to any category yet.
          <% end %>
        </h4>
        
        <h4><strong>Location:</strong>
         <% if !course.locations.empty? %>
            <%= course.locations.collect {|c|
              link_to( c.name, c)}.join(", ").html_safe %>
          <% else %>
           No location added to this course.
          <% end %>
        </h4>
     <p>
        Created: <%= time_ago_in_words(course.created_at) %>
      </p>
        <% if logged_in? %>
            <% if current_user.admin? || current_user == User.find(course.user_id) %>
              <%= link_to 'Edit', edit_course_path(course) %>
                <% if current_user.admin? %>
              
                    <%# <%= button_to 'Reset votes', course.like, method: :delete %>

                    <%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %><br>
                <% end %>
            <% end %>

        <% pre_like = course.likes.find { |like| like.user_id == current_user.id} %>
        <% pre_unlike = course.unlikes.find { |unlike| unlike.user_id == current_user.id} %>
        <% if !pre_like || !pre_unlike%>
          <%= link_to 'Like', course_likes_path(course), method: :post, class:'white-text btn btn-success btn-lg glyphicon glyphicon-thumbs-up' %>
          <%= link_to 'UnLike', course_unlikes_path(course), method: :post, class:'white-text btn btn-success btn-lg glyphicon glyphicon-thumbs-down' %>

          <% else %>
           <%= link_to 'Like', course_likes_path(course), method: :post, class:'white-text btn btn-success btn-lg glyphicon glyphicon-thumbs-up' %>
           <%= link_to 'UnLike', course_unlikes_path(course), method: :post, class:'white-text btn btn-success btn-lg glyphicon glyphicon-thumbs-up' %>
        <% end %>
        <%else%>
          <%= link_to 'Like', login_path, class:'white-text btn btn-success btn-lg glyphicon glyphicon-thumbs-up' %>
          <%= link_to 'UnLike', login_path, class:'white-text btn btn-success btn-lg glyphicon glyphicon-thumbs-down' %>
    
      <% end %>
    <p><%= course.likes.count %> <%= (course.likes.count) == 1 || 0 ? 'Like' : 'Likes'%></p>
    <p><%= course.unlikes.count %> <%= (course.unlikes.count) == 1 || 0 ? 'Unlike' : 'Unlikes'%></p>
   <% end %>
<% end %>