config/routes.rb
Rails.application.routes.draw do
  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  root 'static_pages#home', controller: "application#index"
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'



  resources :locations, :categories, :courses do
    member do
      get :categories
      get :courses
      post :course_add
      post :course_remove
      post :category_add
      post :category_remove
      post :courses_thumbsup
      post :courses_thumbsdown 
    end
  end
  resources :users

  resources :courses do
    resources :likes
    resources :unlikes
  end

  resources :contact, only: [:new, :create, :edit ]
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/views/layouts/_footer.html.erb
<footer>
    <div class="row">
        <%= link_to "Contact us", new_contact_path %>
          
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" id = "menubar">
  <div class="container">
    <% if logged_in? %>
        <%= link_to "yourcourse", courses_path, id: "logo" %>

    <%else%>
      <%= link_to "yourcourse", root_path, id: "logo" %>
    <%end%>
    <nav>
      <ul class="nav navbar-nav navbar-right">

        <li class="dropdown" id = "menuselection">
          <a href= "#" class="dropdown-toggle" data-toggle="dropdown">
              <span class = "glyphicon glyphicon-screenshot" id=whiteicons></span>
            Categories <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li> <a><% Category.all.each do |category| %>
                  <%= link_to category.name, category %>
                 <% end %> </a>
            </li>
            <% if logged_in? %>
              <li class="divider"></li>
              <li><%= link_to 'New Category', new_category_path %></li>
             <% end %>
          </ul>
        </li>
        
        <li class="dropdown" id = "menuselection">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class = "glyphicon glyphicon-map-marker" id=whiteicons></span>
            Locations <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li> <% Location.all.each do |location| %>
                  <%= link_to location.name, location %>
                 <% end %>
            </li>
            <% if logged_in? %>
              <li class="divider"></li>
              <li><%= link_to 'New Location', new_location_path %></li>
            <% end %>
          </ul>
        </li>


       <% if logged_in? %>

          <li id = "menuselection"><%= link_to "New Course", new_course_path %> </li>
          <li id = "menuselection"><%= link_to "Product", new_course_path %> </li>
          <li class="dropdown" id = "menuselection">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <span class = "glyphicon glyphicon-education" id=whiteicons></span>
              <%= @current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu" id = "menuselection">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
              <li class="divider"></li>

              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
           <li id = "menuselection">
               <%= link_to "Log In", login_path %>
               </li>
        <% end %>

      </ul>
    </nav>
  </div>
</header>

<br><br><br>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
     <%= render 'layouts/rails_default' %>
     <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">

        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
          <%= yield %>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>